### ISSUE TITLE
Other kind than KameletBinding are wiped out

### ISSUE THREAD

**Issue by apupier** [KaotoIO/vscode-kaoto#111]

**Comment by apupier** [comment]
this request:

![image](https://user-images.githubusercontent.com/1105127/212377872-e44e195b-bcdc-48a8-9a8b-eb283a712d05.png)

returned response "empty":

```{"steps":[],"metadata":{},"parameters":[],"dsl":null}```

**Comment by Delawen** [comment]
This is something already fixed in the backend. Should I do another release so you update the vscode extension?

**Comment by apupier** [comment]
It can wait the release of the end of this sprint.

Can you point to the issue that fixed it for traceability? I cannot find the issue in recently closed ones https://github.com/KaotoIO/kaoto-backend/issues?q=is%3Aissue+is%3Aclosed neither a related PR https://github.com/KaotoIO/kaoto-backend/pulls?q=is%3Apr+is%3Aclosed

**Comment by Delawen** [comment]
Is it not this one? https://github.com/KaotoIO/kaoto-backend/issues/400

**Comment by apupier** [comment]
> Is it not this one? [KaotoIO/kaoto-backend#400](https://github.com/KaotoIO/kaoto-backend/issues/400)

No. here the kind is changed and everything is wiped out

**Comment by Delawen** [comment]
In the standalone version (latest master both UI and backend) it doesn't happen:

![imagen](https://user-images.githubusercontent.com/726590/212852207-77e3d744-564b-4d73-8168-0caba0739937.png)

**Comment by apupier** [comment]
might be related to https://github.com/KaotoIO/kaoto-ui/issues/1121

**Comment by apupier** [comment]
still need to investigate but seems the problem when I crafted an invalid file. So less problematic. Delaying

**Comment by apupier** [comment]
good chance that it was due to Kaoto backend which was not warmed up for my other attempts, which will be fixed with #144
