### ISSUE TITLE
When opening a Camel Route, the type is set to Integration and the catalog is for kamelet binding

### ISSUE THREAD

**Issue by apupier** [KaotoIO/vscode-kaoto#145]
![TypeSetToIntegration](https://user-images.githubusercontent.com/1105127/220929578-744021b2-7067-48c5-88d2-76e9db7fdbb1.gif)

**Comment by mmelko** [comment]
I will take a look at this.

**Comment by mmelko** [comment]
@apupier you can try with https://github.com/KaotoIO/kaoto-ui/pull/1337 Locally it worked for me.
