### ISSUE TITLE
Opening an existing file is resetting its content to blank

### ISSUE THREAD

**Issue by apupier** [KaotoIO/vscode-kaoto#20]
- create a my.kaoto.yaml file
- open it withjkaoto editor
- do some modifications
- save
- close
- reopen teh file
--> it blinks with correct content and then it resets to a blank integration

**Comment by apupier** [comment]
I believe there is high chance that it is the same root cause than https://github.com/KaotoIO/kaoto-ui/issues/648 , so I think better to wait https://github.com/KaotoIO/kaoto-ui/issues/648 to be fixed and then to retry before investigating more

**Comment by kahboom** [comment]
@apupier do you know if this is still an issue?

**Comment by apupier** [comment]
I cannot reproduce anymore.
