### ISSUE TITLE
Data loss when writing "fast" for a field in config panel of a step

### ISSUE THREAD

**Issue by apupier** [KaotoIO/vscode-kaoto#210]
suspecting a consequence of KaotoIO/kaoto-ui#1475

![valueLostWhenWritingFastInVSCodeAndChanging focusInsideBranches](https://user-images.githubusercontent.com/1105127/226668331-7ccc9f41-8750-49e3-9a8c-ba8b03d60e7c.gif)

**Comment by apupier** [comment]
unfortunately reproducing also without being inside a branch now:
![missing letters when typing fast](https://user-images.githubusercontent.com/1105127/226675543-bda52a22-282a-49d0-ad5c-1170dc0be19a.gif)

**Comment by lordrip** [comment]
Also, this generates duplicated calls on VSCode

**Browser**
![Screenshot from 2023-03-24 14-43-01](https://user-images.githubusercontent.com/16512618/227539343-39d70ded-76ca-46d1-83d3-71e6170650ce.png)

**VS Code**
![Screenshot from 2023-03-24 14-43-42](https://user-images.githubusercontent.com/16512618/227539358-daf2ef8c-4d8e-4b1c-81e2-6deba90b8846.png)

Notice that for VS Code we have 3 times each call while doing the same action as in the browser

**Comment by apupier** [comment]
Behavior should be fixed with integration of next release of Kaoto UI (0.7.5)
