### ISSUE TITLE
Config panel is closing when editing text fields of a step inside a branch

### ISSUE THREAD

**Issue by apupier** [KaotoIO/vscode-kaoto#214]
![closingConfigPanel](https://user-images.githubusercontent.com/1105127/227523480-8c5d0b6a-c8f1-4bf2-a3df-42fc0f09c1d2.gif)

**Comment by apupier** [comment]
reported in Kaoto UI https://github.com/KaotoIO/kaoto-ui/issues/1553

**Comment by Delawen** [comment]
Close as duplicated of https://github.com/KaotoIO/kaoto-ui/issues/1553
