### ISSUE TITLE
request: change default port to something other than 8081

### ISSUE THREAD

**Issue by kdubois** [KaotoIO/vscode-kaoto#253]
Hi, can we change the default port to something a little more unique than 8081?  This port is also used by default by eg. Quarkus unit tests so every time run a Quarkus build when VSCode is running it fails unless I specifically change the port in my application.properties which isn't ideal.

**Comment by apupier** [comment]
there is work in progress to pick a free port https://github.com/KaotoIO/vscode-kaoto/issues/60

**Comment by kdubois** [comment]
Great!  Unless of course 8081 is free at the time vscode starts up and I'm not yet running my unit test :)

**Comment by apupier** [comment]
For information, choosing a free port at runtime is not as easy as planned.
The plan is to continue searching in this direction until end of week; if no solution found, we can relatively easily - if no other surprises - implements to use a different port. It will be less powerful but will mitigate port conflict with other applications.

From top of my head, it would consists of changing code at 2 places:
- change port here: https://github.com/KaotoIO/vscode-kaoto/blob/ce67f86971f354475ab1d192718356f6be168a1c/webpack.config.js#L138
- specify port when launching Kaoto backend https://github.com/KaotoIO/vscode-kaoto/blob/ce67f86971f354475ab1d192718356f6be168a1c/src/extension/extension.ts#L74 using something like `child_process.spawn(nativeExecutable, ['-Dquarkus.http.port=8096']);`
