### ISSUE TITLE
Publish first release of VS Code Plugin for Kaoto

### ISSUE THREAD

**Issue by kahboom** [KaotoIO/vscode-kaoto#27]
Users should have the ability to use Kaoto from within an IDE, likely VSCode.

**Comment by apupier** [comment]
scope:
* published on Microsoft Marketplace and open-vsx
* Kaoto backend started automatically
* use case:
  * create a `my.kaoto.yaml` file in the workspace
  * open this file
  * create a small route of 2 steps
  * save
  * close
  * reopen to check that it reloads correctly
