### ISSUE TITLE
"New route" is switching back to route edited before clicking on the button with Kaoto UI main branch (1.1.0)

### ISSUE THREAD

**Issue by apupier** [KaotoIO/vscode-kaoto#280]
tried on online red.ht/kaoto-snapshot and it works fine so specific to VS Code

https://github.com/KaotoIO/vscode-kaoto/assets/1105127/e076dcee-4d4a-40ed-a606-1fc48c1ab4e4

**Comment by apupier** [comment]
root issue is https://github.com/KaotoIO/kaoto-backend/issues/663

**Comment by lordrip** [comment]
Related issue: https://github.com/KaotoIO/kaoto-ui/issues/1910
