### ISSUE TITLE
Choosing a non-kamelet component when in kamelet binding mode discards the choice (main Kaoto Ui branch)

### ISSUE THREAD

**Issue by apupier** [KaotoIO/vscode-kaoto#286]
On Kaoto nightly, it is working

In VS Code, the element is discarded.

https://github.com/KaotoIO/vscode-kaoto/assets/1105127/75315ac6-11b9-443a-8dd8-0f989be2e916

kamelets are working:
![image](https://github.com/KaotoIO/vscode-kaoto/assets/1105127/5ba71466-9878-4ec9-bec0-76ae7db7b5c0)

**Comment by apupier** [comment]
set as blocker as if the route was designed elsewhere and we open it, the component is removed from source file.

**Comment by lordrip** [comment]
Placing a non-existing step, forces the backend to return an empty flow



![Image](https://github.com/KaotoIO/vscode-kaoto/assets/16512618/25b2b73e-3433-4b96-927e-dbad40b0c9aa)
