### ISSUE TITLE
Improve experience "exporting canvas to png"

### ISSUE THREAD

**Issue by apupier** [KaotoIO/vscode-kaoto#289]
https://github.com/KaotoIO/vscode-kaoto/assets/1105127/5577f4e9-fe6a-4ab9-96e7-bb0d1dafe7f0

**Comment by lhein** [comment]
Could you revisit this issue and check if that is still valid?

**Comment by apupier** [comment]
it is still valid, I already checked when integrating Kaoto 2.0.0 TP1

**Comment by apupier** [comment]
it is now working fine with main branch of 2.2.0
