### ISSUE TITLE
Opening Kaoto's embedded source code editor throws exceptions

### ISSUE THREAD

**Issue by lordrip** [KaotoIO/vscode-kaoto#298]
### Description
The Kaoto's embedded source code editor throws an exception in the `vscode-kaoto` extension.

This is particularly relevant since this might incur performance penalties.

From [the docs](https://github.com/microsoft/monaco-editor#faq)

> #### Why all these web workers and why should I care?
> Language services create web workers to compute heavy stuff outside of the UI thread. They cost hardly anything in terms of resource overhead and you shouldn't worry too much about them, as long as you get them to work (see above the cross-domain case).

### Steps to reproduce
1. Open a file using the `vscode-kaoto` extension
2. Open the chromium dev tools (`ctrl + shift + i`)
3. Open Kaoto's embedded source code editor
4. Notice the warning and errors thrown in the console

![image](https://github.com/KaotoIO/vscode-kaoto/assets/16512618/d5ae089e-0395-4617-90b6-1e6ca2828542)

### Notes
related issue: https://github.com/microsoft/vscode/issues/87282

**Comment by apupier** [comment]
using web workers in VS Code Webview: https://code.visualstudio.com/api/extension-guides/webview#using-web-workers

**Comment by apupier** [comment]
obsolete, the integration of Kaoto 2 does not have an embedded editor
