### ISSUE TITLE
KameletBinding is depricated, it is now called Pipe

### ISSUE THREAD

**Issue by victorchapman** [KaotoIO/vscode-kaoto#343]
<img width="539" alt="Screenshot 2023-08-29 at 10 25 18 AM" src="https://github.com/KaotoIO/vscode-kaoto/assets/65624008/ced6a373-c952-4608-b6cd-dd508a1d32dc">

You might want to change the name here.
<img width="358" alt="Screenshot 2023-08-29 at 10 25 40 AM" src="https://github.com/KaotoIO/vscode-kaoto/assets/65624008/18abdccd-340e-4149-b886-205e3d269e65">

**Comment by apupier** [comment]
Pipes will come when integrating kaoto-next, see https://github.com/KaotoIO/kaoto-next/blob/19c5ec81b81e1bc93de8efa1f4d8ebb312c4dbf2/packages/camel-catalog/assembly/pom.xml#L101
There is no specific code for it in the VS Code Kaoto codebase itself.

**Comment by apupier** [comment]
Next version of kaoto integrated on main branch and will be available in next release of VS Code kaoto
