### ISSUE TITLE
Provide possibility to use breakpoints when debugging VS Code kaoto

### ISSUE THREAD

**Issue by apupier** [KaotoIO/vscode-kaoto#39]
currently breakpoints are ignored making it hard to develop VS Code kaoto extension

**Comment by apupier** [comment]
@thiagoelg Are you able to use breakpoints in the extension code while developing? If yes, can you precise how?

**Comment by thiagoelg** [comment]
I have never used them before, I always go with `console.log`s everywhere hahaha, but that's not ideal. I'll try it and see if I can get anything to work, but even so, how would we add breakpoints to dependencies such as `kaoto-ui`?

**Comment by apupier** [comment]
For code which is inside the webview, in theory the "Developer tools" can be used to put breakpoints. I used that with AtlasMap UI in VS Code AtlasMap.

**Comment by thiagoelg** [comment]
Yeah, you are right.

Right now, to have breakpoints working, the `watch` script in `package.json` needs to be changed to `webpack --env dev` so that source maps are generated.
