### ISSUE TITLE
Users want to be able to create Camel Routes and / or Rest DSL from an OpenAPI spec

### ISSUE THREAD

**Issue by lhein** [KaotoIO/vscode-kaoto#405]
We need an action that can take an OpenAPI spec (as uri or file) and generate Camel Routes, Rest DSL or both from it using the Camel REST DSL OpenApi Maven Plugin. (Is Camel JBang using that one? If yes we might instead just invoke the JBang commands)

**Comment by apupier** [comment]
this will be done in VS Code Language Support extension: https://issues.redhat.com/browse/FUSETOOLS2-2173
