### ISSUE TITLE
Provide shortcuts to open text and Kaoto side-by-side

### ISSUE THREAD

**Issue by apupier** [KaotoIO/vscode-kaoto#414]
similar to `Split editor`

Several possibilities and steps:

- [x] #492
- [x] #493
- [x] #494
- [x] #495
- [x] #496

**Comment by lordrip** [comment]
Opening a `.MD` file we can see a `[Open Preview To The Side]` button
![image](https://github.com/KaotoIO/vscode-kaoto/assets/16512618/e1423fda-2abd-46f3-9b5f-34dfaaca677c)

**Comment by lordrip** [comment]
Now this workflow starts from the text file, in our case, we're gonna need to start from Kaoto itself :thinking:

**Comment by apupier** [comment]
This `Open Preview to the side` is a generic feature in VS Code that we cannot reuse because we are not a preview but an editor.
A specific action will need to be provided

**Comment by apupier** [comment]
Several possibilities and steps:

- [ ] Provide command in the palette to open textual editor in another editor group when Kaoto editor is active
- [ ] Provide quick action in editor menu bar to open textual editor in another editor group when Kaoto editor is active
- [ ] Provide keyboard shortcut to open textual editor in another editor group when Kaoto editor is opened
- [ ] Provide contextual menu on Kaoto editor title to open textual editor in another editor group
- [ ] Provide contextual menu in explorer to open textual editor and kaoto editor side by side on yaml files
