### ISSUE TITLE
Distinct commands to create integrations of different types

### ISSUE THREAD

**Issue by lhein** [KaotoIO/vscode-kaoto#423]
With Kaoto we currently can create the following types:
* Camel Route
* Pipe / KLB
* Kamelet
* (and in future Integration)

We need to be able to create new files for each of these types using VS Code commands. Ideally the files come with basic predefined steps.

**Comment by apupier** [comment]
This is not specific to VS Code Kaoto. The command will be provided by the VS Code Language Support extension.

Technically, we should rely on Camel Jbang to avoid duplicate maintenance efforts. So need to implement first in Camel JBang.

**Comment by apupier** [comment]
related epic in JIRa tracker: https://issues.redhat.com/browse/FUSETOOLS2-1929

**Comment by lhein** [comment]
time to schedule this work again, @apupier ?

**Comment by apupier** [comment]
this is already scheduled. just this is unrelated to kaoto so tracked in Jira
