### ISSUE TITLE
Modification of config are not always detected

### ISSUE THREAD

**Issue by apupier** [KaotoIO/vscode-kaoto#44]
- Create a kaoto file my.kaoto.yaml
- Open it with kaoto Editor
- Add a step
- Save
- Select the step to open Config panel
- provide values in config
--> only the first character modification is detected, all others are ignored.

![configNotSaved](https://user-images.githubusercontent.com/1105127/196133117-23009e6b-16be-41cc-b442-0d8246c56cbc.gif)

**Comment by thiagoelg** [comment]
Fix here: https://github.com/KaotoIO/kaoto-ui/pull/835
