### ISSUE TITLE
Support opening `*.camel-k.yaml` and `*.pipe.yaml`

### ISSUE THREAD

**Issue by igarashitm** [KaotoIO/vscode-kaoto#455]
The file name `*.camel-k.yaml` and `*.pipe.yaml` enables the vscode text editor to validate the syntax against Camel K CRD. We'd also allow opening it with Kaoto.
https://github.com/KaotoIO/vscode-kaoto/blob/main/package.json#L57-L65

**Comment by apupier** [comment]
* it is [already possible](https://github.com/KaotoIO/vscode-kaoto/blob/4a98a9e90dbee462c69be080a7736248d2515335/package.json#L88) to open all `*.yaml` via right-click. In theory contextual menu should be provided even without activation
*` *.camel-k.yaml` and `*.pipe.yaml` are not standard naming from Camel community project. I do not think that we should list them directly.
