### ISSUE TITLE
Add a badge to show the kaoto version

### ISSUE THREAD

**Issue by lordrip** [KaotoIO/vscode-kaoto#463]
It would be nice to have the Kaoto dependency version in the README.md file

**Comment by apupier** [comment]
The dependency version is already available in the readme: https://github.com/KaotoIO/vscode-kaoto?tab=readme-ov-file#embedded

**Comment by djelinek** [comment]
> The dependency version is already available in the readme: https://github.com/KaotoIO/vscode-kaoto?tab=readme-ov-file#embedded

do we want to create static badge to make it just more visible/highlight the version also in header of readme? or we do not want to provide this?

**Comment by lordrip** [comment]
I'd like to easily see the version, but ultimately I'll leave this decision to @apupier 🙇

**Comment by apupier** [comment]
We can do it and if we forgo tto update too often, we can still remove it later. (or reevaluate if it is worthy to spend more time to find an automated way)

**Comment by djelinek** [comment]
> We can do it and if we forgo tto update too often, we can still remove it later. (or reevaluate if it is worthy to spend more time to find an automated way)

I will update the PR to use static badge and we will see during time 🙂
