### ISSUE TITLE
Gain space for the editor

### ISSUE THREAD

**Issue by apupier** [KaotoIO/vscode-kaoto#465]
There are several huge spacing specific to VS Code integration that could be remove to provide more place for the important part, the diagram and the config form.

I provided different colors for the different spaces:

![spaceToRemoveToGainPlace](https://github.com/KaotoIO/vscode-kaoto/assets/1105127/a4ebf564-01a3-4bc0-8779-05999a301a92)

**Comment by apupier** [comment]
spaces due to:
* padding
![image](https://github.com/KaotoIO/vscode-kaoto/assets/1105127/001f541a-54a1-4e99-8dc2-9935266455a0)
* padding top
![image](https://github.com/KaotoIO/vscode-kaoto/assets/1105127/8b6ee049-9197-4d5c-b5f6-5d4541e41e22)

**Comment by lordrip** [comment]
> (I cannot find the latest right and bottom few pixels)

That should be the `patternfly/react-topology` padding, maybe it comes by default

**Comment by apupier** [comment]
last one is `overflow:scroll` on `.shell section.shell__tab-content` for the few pixels bottom and right. As as I understand there is never a scrollbar used for the canvas
